default['lc4_base']['username'] = 'larry'
default['lc4_base']['group'] = 'larry'
default['lc4_base']['gid'] = '1337'
default['lc4_base']['home_dir'] = '/home/larry'
default['lc4_base']['password'] = 'none'
